version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - absolutized
  - absolutizes
  - Adict
  - alignviewer
  - allclose
  - amax
  - annt
  - argwhere
  - ascontiguousarray
  - Ashape
  - asscalar
  - Asum
  - atleast
  - autochunking
  - autocovariances
  - autouse
  - beautifulsoup
  - binarizing
  - blas
  - Blosc
  - bokeh
  - bseg
  - bspline
  - btype
  - busa
  - CCOEFF
  - cdname
  - cdval
  - cdylib
  - celerybeat
  - chunksize
  - chunksizes
  - cidx
  - cmap
  - CMAPS
  - cnmf
  - cnmfviewer
  - colorbar
  - colorcet
  - colormapped
  - commitizen
  - conts
  - coorandinates
  - crds
  - csize
  - curdoc
  - curmap
  - cvxpy
  - darr
  - dask
  - datashade
  - datashaded
  - datashader
  - datashading
  - deconvolve
  - Deconvolved
  - delenv
  - denoise
  - didx
  - dmypy
  - doctest
  - dpath
  - dslist
  - dtype
  - dynspread
  - ecos
  - edgelist
  - eigvals
  - elems
  - epath
  - errorlevel
  - etype
  - exitfirst
  - fhist
  - fidx
  - filt
  - filterwarnings
  - flist
  - fmread
  - fnames
  - framewise
  - frombuffer
  - funcs
  - gaussians
  - Gaussians
  - gdict
  - getaffinity
  - gufunc
  - haya
  - hblk
  - Holo
  - holostreams
  - holoviews
  - htmlcov
  - hvobj
  - hvobjs
  - hvres
  - hvsum
  - icol
  - idxs
  - iheight
  - imdict
  - imread
  - Internsity
  - interp
  - intpath
  - ipykernel
  - ipynb
  - iseg
  - isel
  - itemsize
  - ivar
  - iwidth
  - Jaccard
  - jnote
  - jsonable
  - kdim
  - kdims
  - keepdims
  - Kolmogorov
  - ksize
  - kstest
  - lfilter
  - libx
  - linalg
  - lmax
  - localcluster
  - lsqr
  - lstsq
  - lxml
  - markupsafe
  - mathbf
  - maturin
  - maximas
  - maxs
  - mdict
  - mdim
  - mdims
  - medpy
  - metas
  - minian
  - minidx
  - minidxs
  - Miniscope
  - mkdocs
  - moph
  - moveaxis
  - nanmax
  - nanmin
  - natsort
  - natsorted
  - nbfile
  - nbsphinx
  - nbsplit
  - ncell
  - nchunk
  - ndarray
  - ndcurve
  - ndenumerate
  - ndimage
  - neighbours
  - networkx
  - newaxis
  - nextdir
  - nlab
  - NNLS
  - nonselection
  - nosetests
  - npart
  - nsamp
  - nseg
  - Nsort
  - nstp
  - ntabs
  - numba
  - numblocks
  - NWORKERS
  - OPENBLAS
  - outpath
  - outputdict
  - ovly
  - pathlist
  - pbar
  - perframe
  - perpx
  - perseed
  - pfire
  - Pipfile
  - pipmov
  - pipusub
  - pjoin
  - pnplot
  - pnwgt
  - polyder
  - polyfit
  - popd
  - pushd
  - pyargs
  - pyarray
  - pydata
  - pyenv
  - pyfftw
  - pyfunction
  - pymetis
  - pymodule
  - pypackages
  - pytype
  - realfft
  - rechk
  - rechunk
  - rechunked
  - rechunker
  - rechunking
  - rechunks
  - refelect
  - regrid
  - renamer
  - reqs
  - rerunfailures
  - rfft
  - ropeproject
  - rtds
  - rwdict
  - schunks
  - scisps
  - Scrapy
  - sdist
  - selem
  - setdiag
  - setuptools
  - shiftds
  - showma
  - showuma
  - simpleitk
  - sitk
  - skey
  - skimage
  - skvideo
  - Smirnov
  - smth
  - SOURCEDIR
  - SPHINXBUILD
  - SPHINXOPTS
  - spliter
  - sprs
  - Spyder
  - spyderproject
  - spyproject
  - SQDIFF
  - srcpath
  - ssub
  - stackups
  - statsmodels
  - strm
  - subfolders
  - subg
  - subsetting
  - subviews
  - summ
  - swigvarlink
  - tensordot
  - thres
  - thresholding
  - tifffile
  - timepoint
  - timepoints
  - tmps
  - tocsc
  - todense
  - toeplitz
  - topdown
  - tophat
  - tril
  - triu
  - ufunc
  - uids
  - ulab
  - ulabs
  - ultrafast
  - usub
  - usum
  - VARARRAY
  - varr
  - varray
  - vaviewer
  - vcodec
  - vdims
  - vindex
  - Viridis
  - VLINE
  - vlist
  - vmax
  - vname
  - vpath
  - vsub
  - wblk
  - webassets
  - wgts
  - wname
  - wndh
  - wndw
  - xarr
  - xarray
  - XLABEL
  - xrconcat
  - xyrange
  - YLABEL
  - Ymask
  - zstore
ignoreWords:
  - comput
  - scal
import: []
