"""Shared I/O, chunking, and Dask graph helpers (split across submodules)."""

from .array_ops import local_extreme, med_baseline, sps_lstsq
from .chunking import (
    factors,
    get_chk,
    get_chunksize,
    get_optimal_chk,
    optimize_chunk,
    rechunk_like,
)
from .dask_graph import (
    ANNOTATIONS,
    FAST_FUNCTIONS,
    TaskAnnotation,
    check_key,
    check_pat,
    custom_arr_optimize,
    custom_delay_optimize,
    custom_fused_keys_renamer,
    get_keys_pat,
    inline_pattern,
    rewrite_key,
    split_key,
    unique_keys,
)
from .ffmpeg_util import FFmpegUnavailableError, ensure_ffmpeg
from .datasets import (
    load_avi_ffmpeg,
    load_avi_lazy,
    load_avi_lazy_framewise,
    load_avi_perframe,
    load_tif_lazy,
    load_tif_perframe,
    load_videos,
    open_minian,
    open_minian_mf,
    require_existing_dirs,
    save_minian,
    update_meta,
    xrconcat_recursive,
)
from .local_compute import materialize_local
from .logger import (
    ANSIColor,
    configure_cli_logging,
    configure_logging,
    format_wall_duration,
    print_wall_elapsed,
    print_wall_since,
    wall_section,
)

__all__ = (
    "FFmpegUnavailableError",
    "ANNOTATIONS",
    "FAST_FUNCTIONS",
    "TaskAnnotation",
    "check_key",
    "check_pat",
    "configure_cli_logging",
    "configure_logging",
    "custom_arr_optimize",
    "custom_delay_optimize",
    "custom_fused_keys_renamer",
    "ensure_ffmpeg",
    "factors",
    "format_wall_duration",
    "get_chk",
    "get_chunksize",
    "get_keys_pat",
    "get_optimal_chk",
    "inline_pattern",
    "local_extreme",
    "load_avi_lazy",
    "load_avi_lazy_framewise",
    "load_avi_ffmpeg",
    "load_avi_perframe",
    "load_tif_lazy",
    "load_tif_perframe",
    "load_videos",
    "materialize_local",
    "med_baseline",
    "print_wall_elapsed",
    "print_wall_since",
    "open_minian",
    "open_minian_mf",
    "require_existing_dirs",
    "optimize_chunk",
    "rechunk_like",
    "rewrite_key",
    "save_minian",
    "split_key",
    "sps_lstsq",
    "unique_keys",
    "update_meta",
    "ANSIColor",
    "wall_section",
    "xrconcat_recursive",
)
